[window]
dimensions = { columns = 84, lines = 30}
padding = {x = 0, y = 0}
blur = true
opacity = 0.95


[selection]
save_to_clipboard = true

[terminal]
shell = "fish"

[font]
normal = { family = "ComicShannsMono Nerd Font"}
bold = { family = "ComicShannsMono Nerd Font", style = "bold"}
italic = { family = "ComicShannsMono Nerd Font", style = "italic"}
bold_italic = { family = "ComicShannsMono Nerd Font", style = "bold italic"}
size = 14
offset = { x = 0, y = 1 }

[colors.primary]

foreground = "#EdFcdd"
background = "#1c2e1b"

[colors.normal]

black = "0x32302f"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
cyan = "0x89b482"
magenta = "0xd3869b"
white = "0xd4be98"

[colors.bright]

black = "0x32302f"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
cyan = "0x89b482"
magenta = "0xd3869b"
white = "0xd4be98"
