monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_K5_Pro-*"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
        api.alsa.period-size = 64
        api.alsa.period-num = 3
        node.latency = 32/48000
      }
    }
  }
]
